// ============================================================
// ✅ EDIT THIS FILE to update your portfolio content
// ============================================================

export const siteConfig = {
  name: "Abrar Hossain Zahin",
  shortName: "Zahin",
  title: "Aspiring Full Stack AI Engineer",
  tagline: "Turning data into intelligence, one model at a time.",
  bio: "I am a passionate Data Analyst and AI/ML enthusiast currently pursuing B.Sc. in Computer Science and Engineering at East West University. I enjoy building intelligent systems that solve real-world problems, especially in healthcare, environment, and education.",
  bioLong: "B.Sc. Computer Science and Engineering Student at East West University, Dhaka. Passionate about Machine Learning, Deep Learning, NLP, LLMs & Computer Vision.",
  email: "abrarhossain1200@gmail.com",
  resumeUrl: "/resume.pdf",
  university: "East West University, Dhaka",
  degree: "B.Sc. Computer Science and Engineering",
  location: "Dhaka, Bangladesh",
};

export const socialLinks = [
  { label: "LinkedIn",       url: "https://linkedin.com/in/md-abrar-hossain-zahin",          icon: "linkedin" },
  { label: "GitHub",         url: "https://github.com/Zahin2470",                            icon: "github" },
  { label: "Kaggle",         url: "https://kaggle.com/mdabrarhossainzahin",                  icon: "kaggle" },
  { label: "Facebook",       url: "https://facebook.com/AbrarHossainZahin",                  icon: "facebook" },
  { label: "ResearchGate",   url: "https://researchgate.net/profile/Abrar-Zahin-7",          icon: "researchgate" },
  { label: "Google Scholar", url: "https://scholar.google.com/citations?user=PggflFIAAAAJ",  icon: "scholar" },
  { label: "LeetCode",       url: "https://leetcode.com/u/MdZahin",                          icon: "leetcode" },
  { label: "CodeForces",     url: "https://codeforces.com/profile/MD.Zahin",                 icon: "codeforces" },
  { label: "YouTube",        url: "https://www.youtube.com/@Abrar_Hossain_Zahin",            icon: "youtube" },
  { label: "Freelance",       url: "https://www.my.freelancer.com/u/mdzahin2022",            icon: "freelance" },
];

export const skills = [
  { name: "Python",       category: "AI/ML",  level: 95 },
  { name: "TensorFlow",   category: "AI/ML",  level: 88 },
  { name: "PyTorch",      category: "AI/ML",  level: 85 },
  { name: "Pandas",       category: "AI/ML",  level: 92 },
  { name: "OpenCV",       category: "AI/ML",  level: 80 },
  { name: "Scikit-learn", category: "AI/ML",  level: 90 },
  { name: "TypeScript",   category: "Web",    level: 75 },
  { name: "React",        category: "Web",    level: 78 },
  { name: "Next.js",      category: "Web",    level: 72 },
  { name: "Tailwind",     category: "Web",    level: 80 },
  { name: "Docker",       category: "DevOps", level: 68 },
  { name: "Git",          category: "DevOps", level: 88 },
  { name: "Jupyter",      category: "DevOps", level: 95 },
];

export const projects = [
  {
    id: 1,
    title: "ElderCare SuperApp",
    emoji: "🧓",
    description: "Unified elderly care platform for Bangladesh (TypeScript)",
    descriptionLong: "A unified elderly care platform built for Bangladesh. Integrates health tracking, emergency alerts, caregiver management, and telemedicine into a single accessible TypeScript application.",
    tags: ["TypeScript", "Next.js", "React", "Tailwind CSS", "AI"],
    gradient: "from-fuchsia-500 via-purple-500 to-indigo-600",
    github: "https://github.com/Zahin2470/ElderCare-SuperApp",
    demo: null,
    featured: true,
  },
  {
    id: 2,
    title: "Job Portal",
    emoji: "💼",
    description: "Full-stack job search and management system",
    descriptionLong: "Full-stack job search and management system with employer and candidate dashboards, resume parsing, and smart matching algorithms.",
    tags: ["React", "Node.js", "MongoDB", "REST API"],
    gradient: "from-emerald-400 via-cyan-500 to-blue-600",
    github: "https://github.com/Zahin2470/Job-Portal",
    demo: null,
    featured: true,
  },
  {
    id: 3,
    title: "Green Browsing Tracker",
    emoji: "🌍",
    description: "Chrome extension that tracks browsing energy & carbon footprint with dashboard",
    descriptionLong: "Chrome extension that monitors browsing energy consumption and carbon footprint in real-time, with a detailed analytics dashboard.",
    tags: ["JavaScript", "Chrome Extension", "Data Visualization"],
    gradient: "from-emerald-500 via-teal-500 to-cyan-500",
    github: "https://github.com/Zahin2470/Green-Browsing-Tracker",
    demo: null,
    featured: true,
  },
  {
    id: 4,
    title: "Blood Donation Management Software",
    emoji: "🩸",
    description: "Full-stack blood donation management platform for Bangladesh",
    descriptionLong: "Full-stack platform for managing blood donation operations across Bangladesh, including donor registration, blood bank inventory, and emergency request handling.",
    tags: ["React", "Node.js", "Database", "Healthcare"],
    gradient: "from-red-500 to-rose-500",
    github: "https://github.com/Zahin2470/Blood-Donation-Management-Software",
    demo: null,
    featured: false,
  },
  {
    id: 5,
    title: "Multiplication Game",
    emoji: "🎮",
    description: "Interactive and fun multiplication learning game",
    descriptionLong: "Interactive and adaptive multiplication learning game designed to make math fun and engaging for students with progressive difficulty levels.",
    tags: ["JavaScript", "HTML/CSS", "Education", "Game Dev"],
    gradient: "from-amber-400 via-rose-500 to-purple-600",
    github: "https://github.com/Zahin2470/Multiplication-Game",
    demo: null,
    featured: false,
  },
  {
    id: 6,
    title: "Chat Application",
    emoji: "💬",
    description: "Real-time messaging application with modern UI",
    descriptionLong: "Real-time messaging application with modern UI, user authentication, group chats, and media sharing capabilities.",
    tags: ["React", "WebSocket", "Node.js", "Real-time"],
    gradient: "from-indigo-600 via-violet-500 to-fuchsia-500",
    github: "https://github.com/Zahin2470/Chat-Application",
    demo: null,
    featured: false,
  },
  {
    id: 7,
    title: "3D-Untouch-Puzzle",
    emoji: "🧩",
    description: "3D puzzle game with unique untouchable mechanics",
    descriptionLong: "An interactive, real-time hand gesture recognition application that transforms dual-hand movements into intuitive controls for creating and playing jigsaw puzzles",
    tags: ["Unity", "Python", "Game Development", "3D"],
    gradient: "from-emerald-400 via-cyan-500 to-blue-600",
    github: "https://github.com/Zahin2470/3D-Untouch-Puzzle",
    demo: null,
    featured: false,
  },
  {
    id: 8,
    title: "AI-Powered-Personalized-Memory-Art",
    emoji: "🖼️",
    description: "AI-powered personalized memory art generator",
    descriptionLong: "An e-commerce platform where users upload memories (photos, text, voice notes, important dates), and AI transforms them into personalised artwork that can be purchased as physical or digital products.",
    tags: ["AI", "Python", "E-commerce", "JavaScript"],
    gradient: "from-rose-500 to-fuchsia-600",
    github: "https://github.com/Zahin2470/AI-Powered-Personalized-Memory-Art",
    demo: null,
    featured: false,  
  },
];

export const researchPapers = [
  {
    id: 1,
    emoji: "📄",
    iconGradient: "from-violet-500 to-fuchsia-500",
    title: "SADAP: Optimizing Hybrid Padding Strategies in Post-Quantum TLS to Mitigate Handshake Fingerprinting and Addressing Privacy-Bandwidth Trade-offs",
    focus: "Post-Quantum Cryptography, TLS Security, Fingerprinting Resistance",
    tags: ["Cryptography", "Security", "Post-Quantum", "Padding"],
    url: null,
  },
  {
    id: 2,
    emoji: "🧠",
    iconGradient: "from-blue-500 to-cyan-500",
    title: "TumorXAI: Self-Supervised Deep Learning Framework for Explainable Brain MRI Tumor Classification",
    focus: "Medical Imaging, XAI, Self-Supervised Learning",
    tags: ["Medical AI", "XAI", "Deep Learning", "MRI"],
    url: null,
  },
  {
    id: 3,
    emoji: "🌱",
    iconGradient: "from-emerald-500 to-teal-500",
    title: "GreenNet: Design-Time Compactness Outperforms Post-Hoc Compression for Sustainable Edge AI with Comprehensive Multicriteria Evaluation",
    focus: "Green AI, Knowledge Distillation, Edge Computing, Pruning",
    tags: ["Green AI", "CNN", "Edge AI", "Knowledge Distillation", "Pruning"],
    url: null,
  },
  {
    id: 4,
    emoji: "🔬",
    iconGradient: "from-pink-500 to-rose-500",
    title: "Calibrated Parameter-Efficient Multimodal Speech-Text Fusion for Bengali Regional Dialect and Standard Colloquial Bengali Classification",
    focus: "Multimodal Learning, Transformers, Speech Processing",
    tags: ["Multimodal", "Fusion", "Transformers", "Speech Processing", "Bengali"],
    url: null,
  },
  {
    id: 5,
    emoji: "🎥",
    iconGradient: "from-amber-500 to-yellow-500",
    title: "SentiVec: Sentiment-Aware Vector-Based Review Retrieval System with Four-Way Cross-Dataset Validation",
    focus: "NLP, Sentiment Analysis, Vector Retrieval",
    tags: ["NLP", "Sentiment Analysis", "Vector Retrieval", "IR"],
    url: null,
  },
  {
    id: 6,
    emoji: "🌴",
    iconGradient: "from-lime-500 to-green-500",
    title: "BYOLO-Palm: Self-Supervised Multi-Attribute Date Palm Detection for Scalable UAV-Based Health Monitoring",
    focus: "Computer Vision, Self-Supervised Learning, YOLO, Drone Imagery",
    tags: ["Computer Vision", "YOLO", "Self-Supervised", "Drone"],
    url: null,
  },
  {
    id: 7,
    emoji: "🧬",
    iconGradient: "from-indigo-500 to-purple-500",
    title: "Federated Learning for Magnetic Resonance Imaging: A Systematic Review of Privacy Assurance, Cross-Site Generalization, and Clinical Readiness",
    focus: "Federated Learning, MRI, Privacy, Clinical AI",
    tags: ["Federated Learning", "MRI", "Privacy", "Clinical AI"],
    url: null,
  },
  {
    id: 8,
    emoji: "🩺",
    iconGradient: "from-rose-500 to-orange-500",
    title: "GastroVisionNet8: An Attention-Based CNN for Gastric Cancer Classification with XAI",
    focus: "Medical AI, Attention Mechanism, Explainable AI",
    tags: ["Medical AI", "Attention", "XAI", "Cancer Detection"],
    url: null,
  },
];

export const education = [
  {
    degree: "B.Sc. Computer Science and Engineering",
    institution: "East West University",
    location: "Dhaka, Bangladesh",
    period: "6-2022 to 8-2026",
    description: "Focusing on AI, Machine Learning, and Software Engineering. Active researcher in medical imaging and green AI.",
  },
];
