// ============================================================
// ✅ EDIT THIS FILE to update your portfolio content
// ============================================================

export const siteConfig = {
  name: "Abrar Hossain Zahin",
  shortName: "Zahin",
  title: "Aspiring AI & ML Engineer",
  tagline: "Turning data into intelligence, one model at a time.",
  bio: "I am a passionate Data Analyst and AI/ML enthusiast currently pursuing B.Sc. in Computer Science and Engineering at East West University. I enjoy building intelligent systems that solve real-world problems, especially in healthcare, environment, and education.",
  bioLong: "B.Sc. Computer Science and Engineering Student at East West University, Dhaka. Passionate about Machine Learning, Deep Learning, NLP, LLMs & Computer Vision.",
  email: "your.email@example.com",
  resumeUrl: "/resume.pdf",
  university: "East West University, Dhaka",
  degree: "B.Sc. Computer Science and Engineering",
  location: "Dhaka, Bangladesh",
};

export const socialLinks = [
  { label: "LinkedIn",       url: "https://linkedin.com/in/md-abrar-hossain-zahin",         icon: "linkedin" },
  { label: "GitHub",         url: "https://github.com/Zahin2470",                            icon: "github" },
  { label: "Kaggle",         url: "https://kaggle.com/mdabrarhossainzahin",                  icon: "kaggle" },
  { label: "Facebook",       url: "https://facebook.com/AbrarHossainZahin",                  icon: "facebook" },
  { label: "ResearchGate",   url: "https://researchgate.net/profile/Abrar-Zahin-7",          icon: "researchgate" },
  { label: "Google Scholar", url: "https://scholar.google.com/citations?user=PggflFIAAAAJ", icon: "scholar" },
  { label: "LeetCode",       url: "https://leetcode.com/u/MdZahin",                         icon: "leetcode" },
  { label: "CodeForces",     url: "https://codeforces.com/profile/MD.Zahin",                icon: "codeforces" },
  { label: "YouTube",        url: "https://www.youtube.com/@Abrar_Hossain_Zahin",           icon: "youtube" },
];

export const skills = [
  { name: "Python",       category: "AI/ML",  level: 95 },
  { name: "TensorFlow",   category: "AI/ML",  level: 88 },
  { name: "PyTorch",      category: "AI/ML",  level: 85 },
  { name: "Pandas",       category: "AI/ML",  level: 92 },
  { name: "OpenCV",       category: "AI/ML",  level: 80 },
  { name: "Scikit-learn", category: "AI/ML",  level: 90 },
  { name: "TypeScript",   category: "Web",    level: 75 },
  { name: "React",        category: "Web",    level: 78 },
  { name: "Next.js",      category: "Web",    level: 72 },
  { name: "Tailwind",     category: "Web",    level: 80 },
  { name: "Docker",       category: "DevOps", level: 68 },
  { name: "Git",          category: "DevOps", level: 88 },
  { name: "Jupyter",      category: "DevOps", level: 95 },
];

export const projects = [
  {
    id: 1,
    title: "ElderCare-SuperApp",
    emoji: "🧓",
    description: "Unified elderly care platform for Bangladesh (TypeScript)",
    descriptionLong: "A unified elderly care platform built for Bangladesh. Integrates health tracking, emergency alerts, caregiver management, and telemedicine into a single accessible TypeScript application.",
    tags: ["TypeScript", "Next.js", "React", "Tailwind CSS", "AI"],
    gradient: "from-purple-500 to-pink-500",
    github: "https://github.com/Zahin2470/ElderCare-SuperApp",
    demo: null,
    featured: true,
  },
  {
    id: 2,
    title: "Job-Portal",
    emoji: "💼",
    description: "Full-stack job search and management system",
    descriptionLong: "Full-stack job search and management system with employer and candidate dashboards, resume parsing, and smart matching algorithms.",
    tags: ["React", "Node.js", "MongoDB", "REST API"],
    gradient: "from-emerald-500 to-cyan-500",
    github: "https://github.com/Zahin2470/Job-Portal",
    demo: null,
    featured: true,
  },
  {
    id: 3,
    title: "Green-Browsing-Tracker",
    emoji: "🌍",
    description: "Chrome extension that tracks browsing energy & carbon footprint with dashboard",
    descriptionLong: "Chrome extension that monitors browsing energy consumption and carbon footprint in real-time, with a detailed analytics dashboard.",
    tags: ["JavaScript", "Chrome Extension", "Data Visualization"],
    gradient: "from-green-500 to-teal-500",
    github: "https://github.com/Zahin2470/Green-Browsing-Tracker",
    demo: null,
    featured: true,
  },
  {
    id: 4,
    title: "Blood-Donation-Management-Software",
    emoji: "🩸",
    description: "Full-stack blood donation management platform for Bangladesh",
    descriptionLong: "Full-stack platform for managing blood donation operations across Bangladesh, including donor registration, blood bank inventory, and emergency request handling.",
    tags: ["React", "Node.js", "Database", "Healthcare"],
    gradient: "from-red-500 to-rose-500",
    github: "https://github.com/Zahin2470/Blood-Donation-Management-Software",
    demo: null,
    featured: false,
  },
  {
    id: 5,
    title: "Multiplication-Game",
    emoji: "🎮",
    description: "Interactive and fun multiplication learning game",
    descriptionLong: "Interactive and adaptive multiplication learning game designed to make math fun and engaging for students with progressive difficulty levels.",
    tags: ["JavaScript", "HTML/CSS", "Education", "Game Dev"],
    gradient: "from-yellow-500 to-orange-500",
    github: "https://github.com/Zahin2470/Multiplication-Game",
    demo: null,
    featured: false,
  },
  {
    id: 6,
    title: "Chat-Application",
    emoji: "💬",
    description: "Real-time messaging application with modern UI",
    descriptionLong: "Real-time messaging application with modern UI, user authentication, group chats, and media sharing capabilities.",
    tags: ["React", "WebSocket", "Node.js", "Real-time"],
    gradient: "from-indigo-500 to-violet-500",
    github: "https://github.com/Zahin2470/Chat-Application",
    demo: null,
    featured: false,
  },
];

export const researchPapers = [
  {
    id: 1,
    emoji: "📄",
    iconGradient: "from-violet-500 to-fuchsia-500",
    title: "Privacy-Bandwidth Trade-offs in Post-Quantum TLS: Evaluating Adaptive Padding Strategies Against Handshake Fingerprinting",
    focus: "Post-Quantum Cryptography, TLS Security, Fingerprinting Resistance",
    tags: ["Cryptography", "Security", "Post-Quantum"],
    url: null,
  },
  {
    id: 2,
    emoji: "🧠",
    iconGradient: "from-blue-500 to-cyan-500",
    title: "TumorXAI: Self-Supervised Deep Learning Framework for Explainable Brain MRI Tumor Classification",
    focus: "Medical Imaging, XAI, Self-Supervised Learning",
    tags: ["Medical AI", "XAI", "Deep Learning", "MRI"],
    url: null,
  },
  {
    id: 3,
    emoji: "🌱",
    iconGradient: "from-emerald-500 to-teal-500",
    title: "GreenNet: A Lightweight CNN with Knowledge Distillation for Sustainable Edge AI - A Green Score Benchmarking Study on MNIST and CIFAR-10",
    focus: "Green AI, Knowledge Distillation, Edge Computing",
    tags: ["Green AI", "CNN", "Edge AI", "Knowledge Distillation"],
    url: null,
  },
  {
    id: 4,
    emoji: "🩺",
    iconGradient: "from-rose-500 to-orange-500",
    title: "GastroVisionNet8: An Attention-Based CNN for Gastric Cancer Classification with XAI",
    focus: "Medical AI, Attention Mechanism, Explainable AI",
    tags: ["Medical AI", "Attention", "XAI", "Cancer Detection"],
    url: null,
  },
  {
    id: 5,
    emoji: "🎥",
    iconGradient: "from-amber-500 to-yellow-500",
    title: "SentiVec: Sentiment-Aware Vector-based Movie Review Retrieval System",
    focus: "NLP, Sentiment Analysis, Vector Retrieval",
    tags: ["NLP", "Sentiment Analysis", "IR"],
    url: null,
  },
  {
    id: 6,
    emoji: "🌴",
    iconGradient: "from-lime-500 to-green-500",
    title: "Date Palm Tree monitoring in Drone Imagery Using a Self-Supervised BYOL-Driven YOLOv12s Backbone",
    focus: "Computer Vision, Self-Supervised Learning, YOLO, Drone Imagery",
    tags: ["Computer Vision", "YOLO", "Self-Supervised", "Drone"],
    url: null,
  },
];

export const education = [
  {
    degree: "B.Sc. Computer Science and Engineering",
    institution: "East West University",
    location: "Dhaka, Bangladesh",
    period: "2021 – Present",
    description: "Focusing on AI, Machine Learning, and Software Engineering. Active researcher in medical imaging and green AI.",
  },
];
