// ============================================================
// ✅ EDIT THIS FILE to update your portfolio content
// ============================================================

export const siteConfig = {
  name: "Abrar Hossain Zahin",
  shortName: "Zahin",
  title: "Aspiring Full Stack AI/ML Engineer",
  tagline: "Turning data into intelligence, one model at a time.",
  bio: "I am a passionate Data Analyst and AI/ML enthusiast currently completed B.Sc. in Computer Science and Engineering at East West University. I enjoy building intelligent systems that solve real-world problems, especially in healthcare, environment, and education.",
  bioLong: "B.Sc. in Computer Science and Engineering Student at East West University, Dhaka. Passionate about Machine Learning, Deep Learning, NLP, LLMs & Computer Vision.",
  email: "abrarhossain1200@gmail.com",
  resumeUrl: "/resume.pdf",
  university: "East West University, Dhaka",
  degree: "B.Sc. in Computer Science and Engineering",
  location: "Dhaka, Bangladesh",
};

export const socialLinks = [
  { label: "LinkedIn",       url: "https://linkedin.com/in/md-abrar-hossain-zahin",          icon: "linkedin" },
  { label: "GitHub",         url: "https://github.com/Zahin2470",                            icon: "github" },
  { label: "Kaggle",         url: "https://kaggle.com/mdabrarhossainzahin",                  icon: "kaggle" },
  { label: "Facebook",       url: "https://facebook.com/AbrarHossainZahin",                  icon: "facebook" },
  { label: "ResearchGate",   url: "https://researchgate.net/profile/Abrar-Zahin-7",          icon: "researchgate" },
  { label: "Google Scholar", url: "https://scholar.google.com/citations?user=PggflFIAAAAJ",  icon: "scholar" },
  { label: "LeetCode",       url: "https://leetcode.com/u/MdZahin",                          icon: "leetcode" },
  { label: "CodeForces",     url: "https://codeforces.com/profile/MD.Zahin",                 icon: "codeforces" },
  { label: "YouTube",        url: "https://www.youtube.com/@Abrar_Hossain_Zahin",            icon: "youtube" },
  { label: "Freelance",      url: "https://www.my.freelancer.com/u/mdzahin2022",             icon: "freelance" },
];

export const skills = [
  { name: "Python",       category: "AI/ML",  level: 95 },
  { name: "TensorFlow",   category: "AI/ML",  level: 88 },
  { name: "PyTorch",      category: "AI/ML",  level: 85 },
  { name: "Pandas",       category: "AI/ML",  level: 92 },
  { name: "OpenCV",       category: "AI/ML",  level: 80 },
  { name: "Scikit-learn", category: "AI/ML",  level: 90 },
  { name: "TypeScript",   category: "Web",    level: 75 },
  { name: "React",        category: "Web",    level: 78 },
  { name: "Next.js",      category: "Web",    level: 72 },
  { name: "Tailwind",     category: "Web",    level: 80 },
  { name: "Docker",       category: "DevOps", level: 68 },
  { name: "Git",          category: "DevOps", level: 88 },
  { name: "Jupyter",      category: "DevOps", level: 95 },
];

/* ============================================================
   PROJECTS: image: path inside /public/images/projects/
   ============================================================ */
export const projects = [
  {
    id: 1,
    title: "3D Vision Hand Puzzle",
    emoji: "🧩",
    image: "/images/projects/puzzle3d.png",
    gradient: "from-rose-500 via-purple-500 to-indigo-600",
    label: "Game Development",
    description: "3D puzzle game with unique untouchable mechanics",
    descriptionLong: "An interactive, real-time hand gesture recognition application that transforms dual-hand movements into intuitive controls for creating and playing jigsaw puzzles",
    tags: ["Unity", "Python", "Game Development", "3D"],
    github: "https://github.com/Zahin2470/3D-Vision-Hand-Puzzle",
    demo: null,
    featured: false,
  },  
  {
    id: 2,
    title: "Job Portal",
    emoji: "💼",
    image: "/images/projects/jobportal.png",
    gradient: "from-emerald-400 via-cyan-500 to-blue-600",
    label: "FULL STACK",
    description: "Full-stack job search and management system",
    descriptionLong: "Full-stack job search and management system with employer and candidate dashboards, resume parsing, and smart matching algorithms.",
    tags: ["React", "Node.js", "MongoDB", "REST API"],
    github: "https://github.com/Zahin2470/Job-Portal",
    demo: null,
    featured: true,
  }, 
  {
    id: 3,
    title: "Agentic AI Chatbot",
    emoji: "🤖",
    image: "/images/projects/agentic.png",
    gradient: "from-indigo-500 to-purple-500",
    label: "AI · Chatbot",
    description: "An intelligent chatbot powered by agentic AI for natural conversation",
    descriptionLong: "A cutting-edge chatbot that utilizes agentic AI to provide more human-like interactions and context-aware responses.",
    tags: ["AI", "NLP", "Chatbot", "Python"],
    github: "https://github.com/Zahin2470/Agentic-AI-Chat",
    demo: null,
    featured: false,
  },
  {
    id: 4,
    title: "AI-Powered Memory Art",
    emoji: "🖼️",
    image: "/images/projects/memoryart.png",
    gradient: "from-rose-500 to-fuchsia-600",
    label: "AI · E-commerce",
    description: "AI-powered personalized memory art generator",
    descriptionLong: "An e-commerce platform where users upload memories (photos, text, voice notes, important dates), and AI transforms them into personalised artwork that can be purchased as physical or digital products.",
    tags: ["AI", "Python", "E-commerce", "JavaScript"],
    github: "https://github.com/Zahin2470/AI-Powered-Personalized-Memory-Art",
    demo: null,
    featured: false,
  },
  {
    id: 5,
    title: "Proto Vision",
    emoji: "🧠",
    image: "/images/projects/protovision.png",
    gradient: "from-emerald-400 via-teal-500 to-cyan-600",
    label: "AI · Computer Vision",
    description: "Self-supervised few-shot object recognition powered by a frozen DINOv3 backbone.",
    descriptionLong: "A self-supervised few-shot object recognition pipeline built around a frozen DINOv3 ViT-S/16 backbone. Enables live object recognition from a handful of example images using prototype embeddings and cosine similarity—without fine-tuning or GPU requirements.", //[cite: 1]
    tags: ["AI", "Computer Vision", "DINOv3", "Few-Shot Learning", "Python", "OpenCV", "Pytest"],
    github: "https://github.com/Zahin2470/ProtoVision",
    demo: null,
    featured: false,
  }, 
  {
    id: 6,
    title: "Blood Donation Management Software",
    emoji: "🩸",
    image: "/images/projects/blooddonation.png",
    gradient: "from-red-500 to-rose-500",
    label: "Full Stack",
    description: "Full-stack blood donation management platform for Bangladesh",
    descriptionLong: "Full-stack platform for managing blood donation operations across Bangladesh, including donor registration, blood bank inventory, and emergency request handling.",
    tags: ["React", "Node.js", "Database", "Healthcare"],
    github: "https://github.com/Zahin2470/Blood-Donation-Management-Software",
    demo: null,
    featured: false,
  },
  {
    id: 7,
    title: "Chat Application",
    emoji: "💬",
    image: "/images/projects/chatapp.png",
    gradient: "from-blue-500 via-orange-500 to-amber-500",
    label: "Full Stack",
    description: "Real-time messaging application with modern UI",
    descriptionLong: "Real-time messaging application with modern UI, user authentication, group chats, and media sharing capabilities.",
    tags: ["React", "WebSocket", "Node.js", "Real-time"],
    github: "https://github.com/Zahin2470/Chat-Application",
    demo: null,
    featured: false,
  },
  {
    id: 8,
    title: "Safe Vision AI",
    emoji: "🦺",
    image: "/images/projects/safevision.png",
    gradient: "from-yellow-400 via-blue-500 to-purple-600",
    label: "AI · Safety Analytics",
    description: "Self-supervised computer vision system for real-time human safety and behavior monitoring",
    descriptionLong: "A research-grade computer vision system that compares BYOL, SimCLR, and DINOv3 representations for YOLOv12-based multi-person safety analytics under limited labeled data, combining object detection, multi-object tracking, pose estimation, behavior analysis, and real-time safety alerts.",
    tags: ["AI", "Computer Vision", "SSL", "YOLOv12", "DINOv3", "Safety Analytics", "Real-time"],
    github: null,
    demo: null,
    featured: false,
  },
  {
    id: 9,
    title: "Sign Sense Live",
    emoji: "🤟",
    image: "/images/projects/signsense.png",
    gradient: "from-amber-400 via-orange-500 to-rose-600",
    label: "AI · Motion Recognition",
    description: "Train your own real-time hand sign recognizer using a webcam",
    descriptionLong: "An innovative app that uses AI to recognize sign language in real-time and translate it into spoken or written language, making communication more accessible.",
    tags: ["AI", "Python", "Education", "Computer Vision", "Real-time"],
    github: "https://github.com/Zahin2470/SignSenseLive",
    demo: null,
    featured: false,
  },
  {
    id: 10,
    title: "ElderCare SuperApp",
    emoji: "🧓",
    image: "/images/projects/eldercare.png",
    gradient: "from-rose-500 via-purple-500 to-indigo-600",
    label: "Connected Elderly Care",
    description: "Unified elderly care platform for Bangladesh (TypeScript)",
    descriptionLong: "A unified elderly care platform built for Bangladesh. Integrates health tracking, emergency alerts, caregiver management, and telemedicine into a single accessible TypeScript application.",
    tags: ["TypeScript", "Next.js", "React", "Tailwind CSS", "AI"],
    github: "https://github.com/Zahin2470/ElderCare-SuperApp",
    demo: null,
    featured: true,
  },  
  {
    id: 11,
    title: "Multiplication Game",
    emoji: "🎮",
    image: "/images/projects/multigame.png",
    gradient: "from-amber-400 via-rose-500 to-purple-600",
    label: "Game Development",
    description: "Interactive and fun multiplication learning game",
    descriptionLong: "Interactive and adaptive multiplication learning game designed to make math fun and engaging for students with progressive difficulty levels.",
    tags: ["C", "HTML/CSS", "Education", "Game Dev"],
    github: "https://github.com/Zahin2470/Multiplication-Game",
    demo: null,
    featured: false,
  },
  {
    id: 12,
    title: "Green Browsing Tracker",
    emoji: "🌍",
    image: "/images/projects/greentracker.png",
    gradient: "from-emerald-500 via-teal-500 to-cyan-500",
    label: "Chrome Extension",
    description: "Chrome extension that tracks browsing energy & carbon footprint with dashboard",
    descriptionLong: "Chrome extension that monitors browsing energy consumption and carbon footprint in real-time, with a detailed analytics dashboard.",
    tags: ["JavaScript", "Chrome Extension"],
    github: "https://github.com/Zahin2470/Green-Browsing-Tracker",
    demo: null,
    featured: true,
  }
];

/* ============================================================
   RESEARCH PAPERS: image: path inside /public/images/research/
   ============================================================ */
export const researchPapers = [
  {
    id: 1,
    emoji: "📄",    
    image: "/images/research/sadap.png",
    iconGradient: "from-violet-500 to-fuchsia-500",
    title: "SADAP: Optimizing Hybrid Padding Strategies in Post-Quantum TLS to Mitigate Handshake Fingerprinting and Addressing Privacy-Bandwidth Trade-offs",
    focus: "Post-Quantum Cryptography, TLS Security, Fingerprinting Resistance",
    tags: ["Cryptography", "Security", "Post-Quantum", "Padding"],
    url: null,
  },
  {
    id: 2,
    emoji: "🧠",
    image: "/images/research/tumorxai.png",
    iconGradient: "from-blue-500 to-cyan-500",
    title: "TumorXAI: Self-Supervised Deep Learning Framework for Explainable Brain MRI Tumor Classification",
    focus: "Medical Imaging, XAI, Self-Supervised Learning",
    tags: ["Medical AI", "XAI", "Deep Learning", "MRI"],
    url: "https://arxiv.org/abs/2605.01999",
  },
  {
    id: 3,
    emoji: "🌱",
    image: "/images/research/greennet.png",
    iconGradient: "from-emerald-500 to-teal-500",
    title: "GreenNet: Design-Time Compactness Outperforms Post-Hoc Compression for Sustainable Edge AI with Comprehensive Multicriteria Evaluation",
    focus: "Green AI, Knowledge Distillation, Edge Computing, Pruning",
    tags: ["Green AI", "CNN", "Edge AI", "Knowledge Distillation", "Pruning"],
    url: null,
  },
  {
    id: 4,
    emoji: "🔬",
    image: "/images/research/bengali-dialect.png",
    iconGradient: "from-pink-500 to-rose-500",
    title: "Calibrated Parameter-Efficient Multimodal Speech-Text Fusion for Bengali Regional Dialect and Standard Colloquial Bengali Classification",
    focus: "Multimodal Learning, Transformers, Speech Processing",
    tags: ["Multimodal", "Fusion", "Transformers", "Speech Processing", "Bengali"],
    url: null,
  },
  {
    id: 5,
    emoji: "🎥",
    image: "/images/research/sentivec.png",
    iconGradient: "from-amber-500 to-yellow-500",
    title: "SentiVec: Sentiment-Aware Vector-Based Review Retrieval System with Four-Way Cross-Dataset Validation",
    focus: "NLP, Sentiment Analysis, Vector Retrieval",
    tags: ["NLP", "Sentiment Analysis", "Vector Retrieval", "IR"],
    url: null,
  },
  {
    id: 6,
    emoji: "🌴",
    image: "/images/research/byolopalm.png",
    iconGradient: "from-lime-500 to-green-500",
    title: "BYOLO-Palm: Self-Supervised Multi-Attribute Date Palm Detection for Scalable UAV-Based Health Monitoring",
    focus: "Computer Vision, Self-Supervised Learning, YOLO, Drone Imagery",
    tags: ["Computer Vision", "YOLO", "Self-Supervised", "Drone"],
    url: null,
  },
  {
    id: 7,
    emoji: "🌿",
    image: "/images/research/greenbangla.png",
    iconGradient: "from-cyan-500 to-blue-500",
    title: "GreenHiDRA-Bangla: A Hierarchical, Carbon-Efficient Multi-Task Framework for Parameter-Efficient Bengali Regional Dialect Recognition",
    focus: "Green AI, Multi-Task Learning, Speech Recognition, Transformers, LoRA",
    tags: ["Green AI", "Multi-Task Learning", "Speech Recognition", "Transformers", "LoRA"],
    url: null,
  },
  {
    id: 8,
    emoji: "🧬",
    image: "/images/research/federated-mri.png",
    iconGradient: "from-indigo-500 to-purple-500",
    title: "Federated Learning for Magnetic Resonance Imaging: A Systematic Review of Privacy Assurance, Cross-Site Generalization, and Clinical Readiness",
    focus: "Federated Learning, MRI, Privacy, Clinical AI",
    tags: ["Federated Learning", "MRI", "Privacy", "Clinical AI"],
    url: null,
  },
  {
    id: 9,
    emoji: "🩺",
    image: "/images/research/gastrovision.png",
    iconGradient: "from-rose-500 to-orange-500",
    title: "GastroVisionNet8: An Attention-Based CNN for Gastric Cancer Classification with XAI",
    focus: "Medical AI, Attention Mechanism, Explainable AI",
    tags: ["Medical AI", "Attention", "XAI", "Cancer Detection"],
    url: null,
  },
  {
    id: 10,
    emoji: "💧",
    image: "/images/research/arsenic.png",
    iconGradient: "from-emerald-500 to-teal-500",
    title: "Explainable Spatial AI Framework for Targeted Groundwater Arsenic Testing in Bangladesh",
    focus: "Spatial AI, XAI, Groundwater Arsenic Testing",
    tags: ["Spatial AI", "XAI", "Groundwater Arsenic Testing", "Bangladesh"],
    url: null,
  }
];

export const education = [
  {
    degree: "B.Sc. in Computer Science and Engineering",
    institution: "East West University",
    location: "Dhaka, Bangladesh",
    period: "6-2022 to 8-2026",
    description: "Focusing on AI, Machine Learning, and Software Engineering. Active researcher in medical imaging and green AI.",
  },
];
